require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'LemonList' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # target 'LemonListTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper-Folly' => '2.3.0' })
end

post_install do |installer|
  flipper_post_install(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      config.build_settings.delete('ARCHS')
    end
  end
end


# target 'LemonList-tvOS' do
#   # Pods for LemonList-tvOS

#   target 'LemonList-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end
